base_url: "https://pr-underworld.com/website/monstercount/"
timezone: "Europe/Berlin"

server: "Netherworld"

selectors:
  header_tag: "h4"
  header_text: "Netherworld:"
  table_after_header: true

paths:
  raw_dir: "data/raw"
  hourly_dir: "data/hourly"
  reports_dir: "reports"
  players_dir: "players"

thresholds:
  min_daily_kills: 1500
  inactive_lt: 500
  normal_ge: 501
  normal_lt: 3000
  mid_ge: 3000
  mid_lt: 4000
  high_ge: 4000

report_times:
  weekly_post_weekday: 6              # 0=Montag, 6=Sonntag
  weekly_post_hour_local: 23
  monthly_post_hour_local: 23

discord:
  webhook: ""                         # kommt als Secret aus der Action
  max_length: 1920
  top_players_per_period: 10
