timezone: Europe/Berlin
server: "nw"
base_url: "DEINE_URL"
selectors:
  header_tag: "h2"
  header_text: "Netherworld"

paths:
  raw_dir: "raw"
  hourly_dir: "hourly"
  players_dir: "players"
  reports_dir: "reports"

thresholds:
  min_daily_kills: 1500
  inactive_lt: 500
  normal_ge: 501
  normal_lt: 3000
  mid_ge: 3000
  mid_lt: 4000
  high_ge: 4000

report_times:
  weekly_post_weekday: 6
  weekly_post_hour_local: 23
  monthly_post_hour_local: 23

discord:
  webhook: ""
  max_length: 1920
  top_players_per_period: 10
